{
 "title": "OpenSearch Dashboard",
 "description": "OpenSearch dashboard",
 "tags": [
  "opensearch",
  "App"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(opensearch_cluster_status, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(opensearch_cluster_status{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(opensearch_cluster_status{cluster=~\"$cluster\", namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(opensearch_cluster_status{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "KPI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_status{cluster=~\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "type": "status-history",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(max_over_time(opensearch_cluster_status{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tripped breakers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(opensearch_circuitbreaker_tripped_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}>0)"
    }
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(max(opensearch_process_cpu_percent{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM memory used Avg.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (opensearch_jvm_mem_heap_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) / sum (opensearch_jvm_mem_heap_max_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_nodes_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "stat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_datanodes_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "stat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_pending_tasks_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total number of shards",
   "type": "stat",
   "description": "The total number of shards that exist in the cluster state",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(opensearch_cluster_shards_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active primary shards",
   "type": "stat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "repeat": "shard_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_shards_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\", type=\"active_primary\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "stat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_shards_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\", type=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "stat",
   "description": "Count of shards that are being freshly created",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_shards_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\", type=\"initializing\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "stat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_shards_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\", type=\"relocating\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "stat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_shards_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\", type=\"unassigned\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (opensearch_process_file_descriptors_open_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Amount of active shards",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_shards_active_percent{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(opensearch_jvm_gc_collection_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(opensearch_jvm_gc_collection_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Breakers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tripped breakers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(opensearch_circuitbreaker_tripped_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated size in bytes of breaker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(opensearch_circuitbreaker_estimated_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
     "legendFormat": "{{node}} usage"
    },
    {
     "expr": "max(opensearch_circuitbreaker_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
     "legendFormat": "{{node}} limit"
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "opensearch_os_load_average_one_minute{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "load1: {{node}}"
    },
    {
     "expr": "opensearch_os_load_average_five_minutes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "load5: {{node}}"
    },
    {
     "expr": "opensearch_os_load_average_fifteen_minutes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "load15: {{node}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "opensearch_process_cpu_percent{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "opensearch_jvm_mem_heap_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{node}}: usage"
    },
    {
     "expr": "opensearch_jvm_mem_heap_max_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{node}}: max"
    },
    {
     "expr": "opensearch_jvm_mem_pool_peak_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{node}}: peak"
    }
   ]
  },
  {
   "title": "JVM memory committed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "opensearch_jvm_mem_heap_committed_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{node}}: committed"
    },
    {
     "expr": "opensearch_jvm_mem_heap_max_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{node}}: max"
    }
   ]
  },
  {
   "title": "Disk and Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - max(opensearch_fs_total_available_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}/opensearch_fs_total_total_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(opensearch_transport_tx_bytes_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{node}}: sent"
    },
    {
     "expr": "- rate(opensearch_transport_rx_bytes_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{node}}: received"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Documents count on node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(opensearch_indices_doc_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Documents indexed rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(opensearch_indices_indexing_index_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Documents deleted rate",
   "type": "timeseries",
   "description": "Count of deleted documents on this node",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(opensearch_indices_indexing_delete_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Documents merged rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(opensearch_indices_merges_total_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Documents merged bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(rate(opensearch_indices_merges_total_size_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(opensearch_indices_search_query_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(opensearch_indices_indexing_index_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(opensearch_indices_merges_total_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throttle time for index store",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(opensearch_indices_indexing_throttle_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Operations stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Operations  rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(opensearch_indices_indexing_index_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: indexing"
    },
    {
     "expr": "max(rate(opensearch_indices_search_query_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: query"
    },
    {
     "expr": "max(rate(opensearch_indices_search_fetch_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: fetch"
    },
    {
     "expr": "max(rate(opensearch_indices_merges_total_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: merges"
    },
    {
     "expr": "max(rate(opensearch_indices_refresh_total_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: refresh"
    },
    {
     "expr": "max(rate(opensearch_indices_flush_total_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: flush"
    },
    {
     "expr": "max(rate(opensearch_indices_get_exists_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: get_exists"
    },
    {
     "expr": "max(rate(opensearch_indices_get_missing_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: get_missing"
    },
    {
     "expr": "max(rate(opensearch_indices_get_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: get"
    },
    {
     "expr": "max(rate(opensearch_indices_indexing_delete_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: indexing_delete"
    }
   ]
  },
  {
   "title": "Total Operations time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(opensearch_indices_indexing_index_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: indexing"
    },
    {
     "expr": "max(rate(opensearch_indices_search_query_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: query"
    },
    {
     "expr": "max(rate(opensearch_indices_search_fetch_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: fetch"
    },
    {
     "expr": "max(rate(opensearch_indices_merges_total_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: merges"
    },
    {
     "expr": "max(rate(opensearch_indices_refresh_total_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: refresh"
    },
    {
     "expr": "max(rate(opensearch_indices_flush_total_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: flush"
    },
    {
     "expr": "max(rate(opensearch_indices_get_exists_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: get_exists"
    },
    {
     "expr": "max(rate(opensearch_indices_get_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: get_time"
    },
    {
     "expr": "max(rate(opensearch_indices_get_missing_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: get_missing"
    },
    {
     "expr": "max(rate(opensearch_indices_indexing_delete_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: indexing_delete"
    },
    {
     "expr": "max(rate(opensearch_indices_get_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}: get"
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Thread Pool operations rejected",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 6, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(rate(opensearch_threadpool_threads_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\", type=\"rejected\"}[$__rate_interval])) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Thread Pool operations queued",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 6, "x": 6, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(opensearch_threadpool_tasks_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\" type=\"queue\"}) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Thread Pool threads active",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 6, "x": 12, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(opensearch_threadpool_tasks_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\", type=\"queue\"}) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Thread Pool operations completed",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 6, "x": 18, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(rate(opensearch_threadpool_threads_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\", type=\"completed\"}[$__rate_interval])) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Field data memory size",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_fielddata_memory_size_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Field data evictions",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_fielddata_evictions_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query cache size",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_querycache_memory_size_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query cache evictions",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_querycache_evictions_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Evictions from filter cache",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(opensearch_indices_requestcache_evictions_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Count of index segments",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(opensearch_indices_segments_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current memory size of segments in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(opensearch_indices_segments_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node, type)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Count of documents and Total size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Count of documents",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(opensearch_indices_doc_number{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total size of stored index data in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(opensearch_indices_store_size_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Doc values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Doc store size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(opensearch_indices_store_size_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Fields",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Size of fields",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(opensearch_indices_segments_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}) by (node, type)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}