---
_meta:
  type: "config"
  config_version: 2

# https://github.com/opensearch-project/security/blob/main/config/config.yml

config:
  dynamic:
    kibana:
      multitenancy_enabled: false
      server_username: dashboard
    http:
      anonymous_auth_enabled: true
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false # JWT tokens already contain all required information, so challenge is unnecessary
          config:
            subject_key: sub
            roles_key: roles
            openid_connect_url: http://keycloak:8080/realms/local-development/.well-known/openid-configuration
        authentication_backend:
          type: noop # unnecessary
