---
_meta:
  type: "roles"
  config_version: 2

# https://github.com/opensearch-project/security/blob/main/config/roles.yml

default_write:
  cluster_permissions:
    - cluster:monitor/nodes/info
    - cluster:monitor/health
    - indices:admin/template/get
    - indices:admin/exists
    - indices:admin/delete
    - indices:admin/create
  index_permissions:
    - index_patterns:  
        - "*"
      allowed_actions:
        - write
        - create_index
        - delete

default_read:
  cluster_permissions:
    - cluster:monitor/nodes/info
    - cluster:monitor/health
    - indices:admin/template/get
    - indices:admin/exists
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - read
        - search
        - indices_monitor
        - indices:admin/get

developer:
  cluster_permissions:
    - cluster_monitor
    - indices_monitor
    - cluster:admin/opendistro/ism/policy/get
    - cluster:admin/opendistro/ism/policy/search
    - cluster:admin/opendistro/ism/managedindex/explain
    - indices:admin/resolve/index
    - indices:admin/index_template/get
    - indices:admin/aliases/get
    - indices:admin/data_stream/get
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "indices_monitor"
        - "indices:admin/resolve/index"
    - index_patterns:
        - ".kibana*"
      allowed_actions:
        - "read"
        - "write"
dashboard:
  cluster_permissions:
    - cluster_monitor
  index_permissions:
    - index_patterns:
        - ".kibana*"
        - ".opensearch_dashboards*"
      allowed_actions:
        - indices_all
    - index_patterns:
        - "*"
      allowed_actions:
        - indices:admin/aliases/get