---
# In this file users, backendroles and hosts can be mapped to Security roles.
# Permissions for OpenSearch roles are configured in roles.yml

_meta:
  type: "rolesmapping"
  config_version: 2

# https://github.com/opensearch-project/security/blob/main/config/roles_mapping.yml

# Define your roles mapping here

default_write:
  backend_roles:
    - "opensearch_default_write"

default_read:
  backend_roles:
    - "opensearch_default_read"

developer:
  backend_roles:
    - "opensearch_developer"

## Demo roles mapping

all_access:
  reserved: false
  backend_roles:
    - "admin"
    - "opensearch_all_access"
  description: "Maps admin to all_access"

own_index:
  reserved: false
  users:
    - "*"
  description: "Allow full access to an index named like the username"

dashboard:
  reserved: false
  users:
    - "dashboard"
  description: "Maps kibanaserver to dashboard"
