name: "Build and push image to ghcr.io"

inputs:
  image_name:
    required: true
  context:
    required: true
  base_image:
    default: dockerfiles/Dockerfile.generic
  github_token:
    required: true
  github_actor:
    requred: true
  github_run_id:
    required: false
    default: latest
  read_package_pat:
    description: "..."
    required: true

runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ inputs.github_actor }}
        password: ${{ inputs.github_token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/${{ inputs.image_name }}
        tags: |
          type=ref,event=branch,suffix=-${{inputs.github_run_id}}
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.base_image }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          GITHUB_ACTOR=${{ inputs.github_actor }}
          GITHUB_TOKEN=${{ inputs.read_package_pat }}
