extensions:
  basicauth/client:
    client_auth:
      username: ${env:OBSERVABILITY_USERNAME}
      password: ${env:OBSERVABILITY_PASSWORD}

receivers:
  filelog:
    include: ["/tmp/logs/kafka/*.log"]

processors:
  filter/ottl:
    error_mode: ignore
    logs:
      log_record:
        - 'IsMatch(body, ".*super user.*")'
  transform:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(severity_number, SEVERITY_NUMBER_DEBUG) where IsString(body) and IsMatch(body, "\\sDEBUG\\s")

exporters:
  logging:
    loglevel: debug
  azuremonitor:
    connection_string: ${env:APPLICATIONINSIGHTS_CONNECTION_STRING}
  loki:
    endpoint: https://loki.visionai.cheetah.trifork.dev/api/push
    default_labels_enabled:
      exporter: false
      job: true
    auth:
      authenticator: basicauth/client

service:
  extensions: [basicauth/client]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [filter/ottl, transform]
      exporters: [azuremonitor, logging]
