extensions:
  basicauth/client:
    client_auth:
      username: ${env:OBSERVABILITY_USERNAME}
      password: ${env:OBSERVABILITY_PASSWORD}

receivers:
  filelog:
    include: ["/tmp/logs/opensearch/*.log"]

processors:
  batch:

  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: RequestPath, test

exporters:
  logging:
    loglevel: debug
  azuremonitor:
    connection_string: ${env:APPLICATIONINSIGHTS_CONNECTION_STRING}
  loki:
    endpoint: https://visionai-loki.cheetah.trifork.dev/api/push
    default_labels_enabled:
      exporter: false
      job: true
    auth:
      authenticator: basicauth/client

service:
  extensions: [basicauth/client]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [attributes]
      exporters: [logging]
