version: "2.1"

services:
  zookeeper:
    image: quay.io/strimzi/kafka:0.33.2-kafka-3.2.3
    platform: linux/amd64
    command:
      ["sh", "-c", "bin/zookeeper-server-start.sh config/zookeeper.properties"]
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      LOG_DIR: /tmp/logs
    mem_limit: 512m
    profiles:
      - kafka
      - core
      - full

  kafka:
    image: ${DOCKER_REGISTRY-}cheetah-infrastructure-utils-kafka:strimzi-0.33.0-kafka-3.3.2-trifork-1.4.0
    platform: linux/amd64
    hostname: kafka
    mem_limit: 1024m
    command:
      [
        "sh",
        "-c",
        "bin/kafka-server-start.sh /opt/kafka/custom-config/server.properties",
      ]
    depends_on:
      zookeeper:
        condition: service_started
      cheetah.oauth.simulator:
        condition: service_healthy
    ports:
      - "9092:9092" # Requires OAuth2 authentication
      - "9093:9093" # Requires No authentication
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ROOT_LOGGER_LEVEL: debug
    volumes:
      - ../config/kafka/server.properties:/opt/kafka/custom-config/server.properties
    healthcheck:
      test: nc -z kafka 19092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    profiles:
      - kafka
      - core
      - full

  kafka-setup:
    image: quay.io/strimzi/kafka:0.33.2-kafka-3.3.2
    platform: linux/amd64
    container_name: kafka-setup
    volumes:
      - ../config/kafkaconfig.sh:/etc/config/kafkaconfig.sh
      - ../config/kafka/kafkasetup.config:/etc/config/kafkasetup.config
    command: "bash /etc/config/kafkaconfig.sh"
    depends_on:
      kafka:
        condition: service_healthy
      cheetah.oauth.simulator:
        condition: service_healthy
    environment:
      # The following settings are listed here only to satisfy the image's requirements.
      # We override the image's `command` anyways, hence this container will not start a broker.
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
    profiles:
      - kafka
      - full

  redpanda:
    image: redpandadata/console-unstable:master-f155c44
    entrypoint: /bin/sh
    command: -c "/app/console"
    mem_limit: 512m
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
    volumes:
      - ../config/redpanda.yaml:/tmp/config.yml
    ports:
      - "9898:8080"
    healthcheck:
      test: curl redpanda:8080/admin/health || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      kafka-setup:
        condition: service_completed_successfully
    profiles:
      - kafka
      - full

  # Kafka Prometheus exporter https://github.com/cloudhut/kminion
  kafka-minion:
    image: quay.io/cloudhut/kminion:master
    hostname: kafka-minion
    container_name: kafka-minion
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 8088:8080
    environment:
      KAFKA_BROKERS: kafka:19093
    profiles:
      - observability
      - full

  schema-registry:
    mem_limit: 256m
    image: apicurio/apicurio-registry-kafkasql:2.4.3.Final
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      kafka:
        condition: service_healthy
      cheetah.oauth.simulator:
        condition: service_healthy
      kafka-setup:
        condition: service_completed_successfully
    ports:
      - "8081:8080" # http://localhost:8081/ui/
    environment:
      # Kafka
      ENABLE_KAFKA_SASL: true
      CLIENT_ID: sr
      CLIENT_SECRET: testSecret
      OAUTH_TOKEN_ENDPOINT_URI: http://cheetahoauthsimulator/oauth2/token
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
      REGISTRY_KAFKASQL_TOPIC: _kafkasql-journal
      REGISTRY_KAFKASQL_TOPIC_AUTO_CREATE: false
      # Basics
      REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED: true
      REGISTRY_UI_FEATURES_READONLY: true
      # API protection
      AUTH_ENABLED: true # also protects UI
      ROLE_BASED_AUTHZ_ENABLED: true # Allows admin and developer concept
      REGISTRY_AUTH_OBAC_ENABLED: true
      REGISTRY_AUTH_OBAC_LIMIT_GROUP_ACCESS: true
      ROLE_BASED_AUTHZ_SOURCE: "token"
      REGISTRY_AUTH_ROLES_DEVELOPER: "sr-producer" # "sr-developer"
      # https://quarkus.io/guides/security-oidc-configuration-properties-reference
      quarkus.oidc.enabled: true
      quarkus.oidc.auth-server-url: http://cheetahoauthsimulator:80
      quarkus.oidc.jwks-path: /.well-known/jwks.json
      #quarkus.log.level: DEBUG
      quarkus.oidc.roles.role-claim-path: roles

    healthcheck:
      test: curl schema-registry:8080 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    profiles:
      - kafka
      - full

networks:
  default:
    name: "cheetah-infrastructure"
