---
version: "3.4"

services:
  cheetah.oauth.simulator:
    hostname: cheetahoauthsimulator
    ports:
      - "1752:80"
    image: ${DOCKER_REGISTRY-}cheetah-oauth-simulator:1.7.2
    platform: linux/amd64
    restart: unless-stopped
    environment:
      # - ASPNETCORE_ENVIRONMENT=Development
      - OAuth__Mode=Asymmetric
      - Simulator__DefaultKafkaRole=*_all
    profiles:
      - kafka-core
      - schema-registry-core
      - opensearch-core
      - core
      - kafka
      - opensearch
      - full

  # Not enabled by default
  cheetah.oauth.simulator.https:
    hostname: cheetahoauthsimulator
    ports:
      - "1852:1852"
    image: ${DOCKER_REGISTRY-}cheetah-oauth-simulator:1.7.2
    platform: linux/amd64
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:1852;http://+:1752
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/appuser/.aspnet/https/aspnetapp.pfx
      - OAuth__SymmetricPrivateKey="wnhjzYtZD7tMbqu4C5xw"
      - OAuth__Mode=Asymmetric
      - Simulator__CertFilePath=/appuser/.aspnet/certs/secret.pem
    volumes:
      - "${APPDATA:-.}/ASP.NET/https:/appuser/.aspnet/https:ro"
      - "${APPDATA:-.}/ASP.NET/certs:/appuser/.aspnet/certs"
    profiles:
      - oauth_https

networks:
  default:
    name: "cheetah-infrastructure"
