---
services:
  prometheus:
    mem_limit: 128m
    container_name: prometheus
    image: quay.io/prometheus/prometheus:v2.55.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    # restart: always
    volumes:
      - ./config/prometheus:/etc/prometheus/
    #  - prometheus_data:/prometheus
    profiles:
      - observability
      - full
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    mem_limit: 256m
    container_name: grafana
    image: docker.io/grafana/grafana:10.4.15
    # restart: always
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      # - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 32769:3000
    profiles:
      - observability
      - full

  node_exporter:
    mem_limit: 128m
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro"
    profiles:
      - observability
      - full

networks:
  default:
    name: "cheetah-infrastructure"
