services:
  # login fallback: admin:admin
  # services should use oauth
  opensearch:
    image: opensearchproject/opensearch:2.6.0
    hostname: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=os01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      #- DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    mem_limit: 2048m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - opensearch:/data
      - ../config/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ../config/opensearch/security/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
      - ../config/opensearch/security/roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml
      - ../config/opensearch/security/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
      - ../config/opensearch/security/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
      # Demo certs
      - ../config/opensearch/certs/esnode-key.pem:/usr/share/opensearch/config/esnode-key.pem
      - ../config/opensearch/certs/esnode.pem:/usr/share/opensearch/config/esnode.pem
      - ../config/opensearch/certs/kirk-key.pem:/usr/share/opensearch/config/kirk-key.pem
      - ../config/opensearch/certs/opensearch.keystore:/usr/share/opensearch/config/opensearch.keystore
      - ../config/opensearch/certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
    ports:
      - 9229:9200
      - 9600:9600
    profiles:
      - opensearch

  # login kibanaserver:kibanaserver
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    hostname: opensearch-dashboards
    ports:
      - 5602:5601
    volumes:
      - ../config/opensearch_dashboards/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
      - ../config/opensearch_dashboards/opensearch_dashboards.crt:/usr/share/opensearch-dashboards/config/opensearch_dashboards.crt
      - ../config/opensearch_dashboards/opensearch_dashboards.key:/usr/share/opensearch-dashboards/config/opensearch_dashboards.key

    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      #- DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    profiles:
      - opensearch

volumes:
  opensearch:

networks:
  default:
    name: "cheetah-infrastructure"
