---
version: "2.1"

services:
  # login fallback: admin:admin
  # services should use oauth
  opensearch:
    image: ${CHEETAH_DOCKER_REGISTRY-}cheetah-infrastructure-opensearch:0.5.0
    container_name: opensearch
    hostname: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=os01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      # - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    depends_on:
      keycloak-setup:
        condition: service_completed_successfully
    mem_limit: 2048m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - opensearch:/data
      - ./config/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./config/opensearch/security/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
      - ./config/opensearch/security/roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml
      - ./config/opensearch/security/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
      - ./config/opensearch/security/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
      # Demo certs
      - ./config/opensearch/certs/esnode-key.pem:/usr/share/opensearch/config/esnode-key.pem
      - ./config/opensearch/certs/esnode.pem:/usr/share/opensearch/config/esnode.pem
      - ./config/opensearch/certs/kirk-key.pem:/usr/share/opensearch/config/kirk-key.pem
      - ./config/opensearch/certs/opensearch.keystore:/usr/share/opensearch/config/opensearch.keystore
      - ./config/opensearch/certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
    ports:
      - 9200:9200
      - 9600:9600
    profiles:
      - opensearch-core
      - core
      - opensearch
      - full
    healthcheck:
      test: curl -u admin:admin -s -f opensearch:9200/_cat/health > /dev/null || exit 1
      interval: 30s # (default: 30s)
      timeout: 10s # (default: 30s)
      retries: 3 #  (default: 3)
      start_period: 30s # (default: 0s)

  opensearch-configurer:
    image: ${CHEETAH_DOCKER_REGISTRY-}cheetah-infrastructure-utils-os:0.5.0
    container_name: opensearch-configurer
    command: "opensearch:9200 --service"
    environment:
      - OS_USER=opensearch-admin
      - OS_PASS=opensearch-admin-secret
      - OS_SCOPE=opensearch
      - OS_TOKENENDPOINT=http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      - OAUTHLIB_INSECURE_TRANSPORT=true
    depends_on:
      opensearch:
        condition: service_healthy
    volumes:
      # TODO: when the base directory is configurable, use the following instead
      # - ./config/opensearch-configurer/:/path/to/basedir/
      - ./config/opensearch-configurer/lifecycle_policies/:/app/tmp/lifecycle_policies/
      - ./config/opensearch-configurer/pipelines/:/app/tmp/pipelines/
      - ./config/opensearch-configurer/component_templates/:/app/tmp/component_templates/
      - ./config/opensearch-configurer/index_templates/:/app/tmp/index_templates/
      - ./config/opensearch-configurer/cluster/:/app/tmp/cluster/
    profiles:
      - opensearch-core
      - core
      - opensearch
      - full

  # login kibanaserver:kibanaserver
  opensearch-dashboards:
    container_name: opensearch-dashboards
    image: opensearchproject/opensearch-dashboards:2.11.1
    hostname: opensearch-dashboards
    ports:
      - 5602:5601
    volumes:
      - ./config/opensearch_dashboards/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
      - ./config/opensearch_dashboards/opensearch_dashboards.crt:/usr/share/opensearch-dashboards/config/opensearch_dashboards.crt
      - ./config/opensearch_dashboards/opensearch_dashboards.key:/usr/share/opensearch-dashboards/config/opensearch_dashboards.key
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
    # - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      opensearch:
        condition: service_healthy
    profiles:
      - opensearch
      - full

volumes:
  opensearch:

networks:
  default:
    name: "cheetah-infrastructure"
