services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    restart: unless-stopped
    mem_limit: 1024m
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: timescaledb
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - timescaledb:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./config/pgadmin/servers.json:/pgadmin4/servers.json

networks:
  default:
    name: "cheetah-infrastructure"

volumes:
  timescaledb:
  pgadmin-data: