services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    restart: unless-stopped
    mem_limit: 1024m
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: cheetah
    volumes:
      - timescaledb:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pgadmin4_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  default:
    name: "cheetah-infrastructure"
    external: true

volumes:
  timescaledb:
  pgadmin-data: