# Local admin access from inside the container.
local   all             postgres                                peer
local   all             all                                     peer

# OAuth-only authentication for all network clients.
host    all             all             0.0.0.0/0               oauth issuer=http://keycloak:1852/realms/local-development scope="postgres"
host    all             all             ::/0                    oauth issuer=http://keycloak:1852/realms/local-development scope="postgres"
