listen_addresses = '*'
port = 5432

dynamic_library_path = '/usr/lib/postgresql/extra:$libdir'
oauth_validator_libraries = 'pg_oidc_validator'
pg_oidc_validator.authn_field = 'preferred_username'

hba_file = '/etc/postgresql/pg_hba.conf'
