listen_addresses = '*'
port = 5432

dynamic_library_path = '/usr/lib/postgresql/extra:$libdir'
oauth_validator_libraries = 'pg_oidc_validator'
pg_oidc_validator.authn_field = 'azp'
pg_oidc_validator.discovery_url_override = 'http://keycloak:1852/realms/local-development'

hba_file = '/etc/postgresql/pg_hba.conf'
