# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - kafka:19092
  schemaregistry:
    enabled: true
    urls: [
      http://schema-registry:8081
    ]
# server:
  # listenPort: 8080