---
# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - kafka:19092
  sasl:
    enabled: true
    mechanism: OAUTHBEARER
  # username: redpanda
  # password: password
    oauth:
      tokenEndpoint: http://cheetahoauthsimulator:80/oauth2/token
      clientId: redpanda
      clientSecret: 1234
  schemaregistry:
    enabled: true
    urls: [http://schema-registry:8080/apis/ccompat/v7]
    # See http://localhost:8081/apis/ for API documentation
# server:
# listenPort: 8080
