---
# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - kafka:19092
  sasl:
    enabled: true
    mechanism: OAUTHBEARER
    # this file is used to simulate the security model on a cluster which uses OAuth for security
    # username: redpanda
    # password: password
    oauth:
      tokenEndpoint: http://keycloak:1852/realms/local-development/protocol/openid-connect/token
      clientId: redpanda
      clientSecret: redpanda-secret
      scope: kafka
  schemaregistry:
    enabled: true
    urls: [http://schema-registry:8080/apis/ccompat/v7]
    # See http://localhost:8081/apis/ for API documentation
# server:
# listenPort: 8080
  connect:
    enabled: true
    clusters:
      - name: "connect-cluster"
      #Try deploying the ui, portforwarding it and putting url below
        url: "http://localhost:8000" 

