# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - kafka:19094 # Special redpanda listener using SCRAM-SHA-512 authentication
  sasl:
    enabled: true
    mechanism: SCRAM-SHA-512
    username: redpanda
    password: password
  schemaregistry:
    enabled: true
    urls: [http://schema-registry:8080/apis/ccompat/v7]
    # See http://localhost:8081/apis/ for API documentation
# server:
# listenPort: 8080
