---
# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - kafka:19092
  sasl:
    enabled: true
    mechanism: OAUTHBEARER
    # this file is used to simulate the security model on a cluster which uses OAuth for security
    # username: redpanda
    # password: password
    oauth:
      tokenEndpoint: http://keycloak:8080/realms/local-development/protocol/openid-connect/token
      clientId: kafka-admin
      clientSecret: kafka-admin-secret
      scope: kafka schema-registry
  schemaregistry:
    enabled: true
    urls: [http://schema-registry:8080/apis/ccompat/v7]
    # See http://localhost:8081/apis/ for API documentation
# server:
# listenPort: 8080
