---
# See: https://docs.redpanda.com/current/console/config/ for reference config files.
kafka:
  brokers:
    - kafka:19094
  sasl:
    enabled: true
    mechanism: SCRAM-SHA-512
    username: redpanda
    password: password

schemaRegistry:
  enabled: true
  urls: 
    - http://schema-registry:8080/apis/ccompat/v7
  authentication:
    # See http://localhost:8081/apis/ for API documentation
