---
name: E2E

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches: ["main", "release/v**"]
  pull_request:
    branches: ["main", "release/v**"]
    types: [opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CHEETAH_DOCKER_REGISTRY: ghcr.io/trifork/

jobs:
  should-run:
    uses: trifork/cheetah-infrastructure-utils-workflows/.github/workflows/e2e-should-run.yml@main

  e2e-test:
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}
    timeout-minutes: 5

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_PAT }} # we need this, as GITHUB_TOKEN only have permission to its own repo
      - name: Generate Keycloak dev certs
        # Run container to generate certs, and copy them to host for later use in tests
        run: docker compose --profile keycloak-cert up --quiet-pull keycloak-cert-init

      - name: Run development environment
        run: docker compose --profile opensearch --profile kafka --profile oauth --profile schemaregistry --profile postgres up --quiet-pull --force-recreate --wait --wait-timeout 240 -d

      - name: Start mye2eclient container in shared network
        run: docker run -d -v "${PWD}/tests/:/opt/tests/" -it --name mye2eclient --network=cheetah-infrastructure alpine:latest

      - name: Setup mye2eclient container
        run: |
          docker exec mye2eclient apk add curl jq bash httpie

      - name: opensearch test
        run: docker exec mye2eclient bash /opt/tests/opensearch.sh

      - name: kafka test
        run: docker exec mye2eclient bash /opt/tests/kafka.sh

      - name: schemaregistry test
        run: docker exec mye2eclient bash /opt/tests/schemaregistry.sh

      - name: postgres test
        run: bash tests/postgres.sh

