name: "e2e"
on:
  workflow_dispatch:

  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_PAT }} # we need this, as GITHUB_TOKEN only have permission to its own repo
        # OpenSearch is required for integration tests
      - name: docker network create cheetah-infrastructure
        run: docker network create cheetah-infrastructure
      - name: Run OAuthSimulator
        run:
          docker run
          --detach
          -p 80:80
          -e "OAuth__Mode=Asymmetric"
          -e "Simulator__DefaultRole=admin"
          --network=cheetah-infrastructure
          --hostname=cheetahoauthsimulator
          ghcr.io/trifork/cheetah-oauth-simulator:latest
          # todo: switch to local compose
      - name: Run OpenSearch # This reuses the options from cheetah-development-infrastructure OS container
        run: docker run
          --detach
          -p 9200:9200
          -e cluster.name=opensearch-cluster
          -e node.name=os01
          -e discovery.type=single-node
          -e bootstrap.memory_lock=true
          -e "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
          -e DISABLE_INSTALL_DEMO_CONFIG=false
          -e network.host=0.0.0.0
          -e plugins.security.ssl.http.enabled=false
          -v $(pwd)/.github/config/:/usr/share/opensearch/config/opensearch-security/
          --network=cheetah-infrastructure
          --hostname=opensearch
          opensearchproject/opensearch:2.6.0

      - name: "Wait for environtment"
        run: sleep 5

      - name: Start mye2eclient container in shared network
        run: docker run -d -v "${PWD}/tests/:/opt/tests/" -it --name mye2eclient --network=cheetah-infrastructure alpine:latest

      - name: Setup mye2eclient container
        run: |
          docker exec mye2eclient apk add curl jq bash

      - name: opensearch test
        run: docker exec mye2eclient bash /opt/tests/opensearch.sh

      #- name: "see logs"
      #  run: docker logs cheetah-lib-templates-java-e2e-job-name-job
